#!/usr/bin/sh

# DP-2 = Right monitor
# DP-1 = Middle monitor (main)
# HDMI-A-1 = Left monitor
# DP-3 = Top monitor

# Default all monitor connecting.
notify-send "Changing window mode " $1
if [[ $1 == "4Monitor" ]]; then
	hyprctl keyword monitor HDMI-A-1, 1920x1080@60, 0x1440,1
	hyprctl keyword monitor DP-1, 2560x1440@240, 1920x1080,1
	hyprctl keyword monitor DP-2, 1920x1080@60, 4480x1440,1
	hyprctl keyword monitor DP-3, 1920x1080, 1920x0,1
# bottom 3 monitor only, happen when top monitor using phone connect.
elif [[ $1 == "3Monitor" ]]; then
	hyprctl keyword monitor HDMI-A-1, 1920x1080@60, 0x360,1
	# hyprctl keyword monitor DP-4, 1920x1080@60, 0x360,1
	hyprctl keyword monitor DP-1, 2560x1440@240, 1920x0,1
	hyprctl keyword monitor DP-2, 1920x1080@60, 4480x360,1
	hyprctl keyword monitor DP-3, disable

elif [[ $1 == "2MonitorLeft" ]]; then
	hyprctl keyword monitor HDMI-A-1, 1920x1080@60, 0x360,1
	# hyprctl keyword monitor DP-4, 1920x1080@60, 0x360,1
	hyprctl keyword monitor DP-1, 2560x1440@240, 1920x0,1
	hyprctl keyword monitor DP-2, disable
	hyprctl keyword monitor DP-3, disable
elif [[ $1 == "2MonitorRight" ]]; then
	hyprctl keyword monitor HDMI-A-1, disable
	# hyprctl keyword monitor DP-4, 1920x1080@60, 0x360,1
	hyprctl keyword monitor DP-1, 2560x1440@240, 0x0,1
	hyprctl keyword monitor DP-2, 1920x1080@60, 2560x360,1
	hyprctl keyword monitor DP-3, disable
# One monitor, work usually or need for gw2 when other are busy.
elif [[ $1 == "1Monitor" ]]; then
	hyprctl keyword monitor HDMI-A-1, disable
	hyprctl keyword monitor DP-1, 2560x1440@240, 0x0,1
	hyprctl keyword monitor DP-2, disable
	hyprctl keyword monitor DP-3, disable
fi

notify-send "Changing monitor setting"
# sh ~/Script/monitorSet
