#!/usr/bin/bash

#Thur 23 Sept 2021 04:33:05 PM EDT
#Author: Maverun
#File: dictionary

# This is dictionary, that will ask for define word and you can search it up
# It will ask for input via dmenu then once it look up term then it will zed for you. or using yad

#We getting input from user with dmenu
INPUT=$(printf ""|dmenu -m 0 -p "Definitons:") || exit

if [ -z "$INPUT" ] #if TODO is empty, then we will ignore it.
then
    exit
fi

dict -d gcide $INPUT | yad --text-info --back=#282C34 --fore=#46D9FF --geometry=1200x800




