[[manager.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[manager.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on  = "<C-n>"
desc = "Dragon"
run = '''
	shell 'dragon -x -i -T "$1"' --confirm
'''

[[manager.prepend_keymap]]
on = [ "g", "r" ]
desc = "Back to Root Git directory"
run = '''
	shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
'''
