#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
export _JAVA_AWT_WM_NONREPARENTING=1|export AWT_TOOLKIT=MToolkit|wmname LG3D
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"


feh --bg-center $(find ~/Wallpaper/Wallpaper -type f | shuf -n 1)

bspc monitor HDMI-0 -d l0 l1 l2
bspc monitor HDMI-1 -d m0 m1 m2
bspc monitor DVI-D-0 -d r0 r1 r2



bspc config border_width        3		
bspc config window_gap          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#E84F4F
#bspc config active_border_color \#E84F4F
#bspc config normal_border_color \#cccccc

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side


#bspc config  external_rules_command "$BSPWM_CONFIG/external_rules"
#bspc config external_rules_command "$BSPWM_CONFIG/external_rules"
#bspc config external_rules_command "$(command -v rules)"
bspc config external_rules_command "~/.config/bspwm/external_rules"
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mpv desktop="r0" state=floating 
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Peek state=floating
bspc rule -a feh state=floating
bspc rule -a Tilda state=floating
bspc rule -a lightcord desktop='l0'
bspc rule -a Xfce4-terminal:*:cmus desktop='r1' hidden=on state=floating
bspc rule -a Org.gnome-clocks desktop='r1' hidden=on state=floating
bspc rule -a Pavucontrol desktop='r1' hidden=on state=floating
bpsc rule -a Trackma desktop='l0'
bspc rule -a Thunderbird desktop='l1'

toggle=$(bspc config focus_follows_pointer | \
         awk -vtoggle="true" \
        '{ if ($1 == "true") \
        toggle="false"; \
        print toggle}')

#bspc config focus_follows_pointer $toggle
#start  up the script.
sh /home/maverun/.startup_script
