#!/bin/sh

notify-send "\$1=$(printf '0x%08X' "$1") \$2=$2 \$3=$3" "$4"



wid=$1
class=$2
instance=$3
consequences=$4

if ["$instance" = cmus ]; then
    printf "desktop='^7'"
fi

if ["$class" = "xfce4-terminal"]; then
    printf "desktop='^7' follow=off"
fi

case "$instance" in
	libreoffice)
		printf "desktop='l1' follow=on"
		;;
	*)
		# Parse class
		case "$class" in
			*)
				# Parse window name
				name=$(xdotool getwindowname "$wid")
				case "$name" in
					Butter|Popcorn-Time)
						printf "desktop='play' follow=on"
						;;
				esac
				;;
		esac
		;;
esac
